spring:
  application:
    name: jy-blog

  # H2 Database
  # datasource:
  #   url: jdbc:h2:mem:testdb
  #   driver-class-name: org.h2.Driver
  #   username: sa
  #   password:
  
  # h2:
  #   console:
  #     enabled: true
  #     path: /h2-console

  # MySQL Database
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: blog
    password: blog123

  jpa:
    hibernate:
      ddl-auto: update  # H2일 때는 create-drop, MySQL일 때는 update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect  # MySQL 사용시 추가
    database-platform: org.hibernate.dialect.MySQLDialect

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.javaex.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.javaex: DEBUG